### ISSUE TITLE
haha

### ISSUE THREAD

**Issue by subbotted** [funkemunky/HCFCore#1]
considering this is an sCore fork its kind of upsetting to see you take credit for it. I guess skids will skid though amirite?

**Comment by ghost** [comment]
erm no... this is my core lol. based on veilhcf.

**Comment by ghost** [comment]
https://github.com/funkemunky/HCFCore/blob/master/HCCore/src/raton/meme/hcf/systems/Systems.java

**Comment by subbotted** [comment]
erm yes... I meant TheCore but still
